language:
 - python

python:
  - 3.6

install:
  -
  - psql -c 'create database test_db;' -U postgres
  - psql -c 'create database' mydiarydb;' -U postgres
  - pip install -r requirements.txt
  - pip install coveralls



script:
  - pytest
  - coverage run --source=Api_v1.app -m pytest  && coverage report


after_success:
  - coveralls

after_success:
  coveralls